apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertlogger
  namespace: monitoring
  labels:
    app: alertlogger
spec:
  automountServiceAccountToken: false
  serviceName: alertlogger
  replicas: 1
  selector:
    matchLabels:
      app: alertlogger
  template:
    metadata:
      labels:
        app: alertlogger
    spec:
      containers:
      - name: alertlogger
        image: ghcr.io/mwennrich/alertlogger:latest
        env:
        - name: JSON_OUTPUT
          value: "true"
        ports:
        - containerPort: 5001
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
